// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	DeleteTask(ctx context.Context, id string) (int64, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetTasks(ctx context.Context) ([]Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
}

var _ Querier = (*Queries)(nil)
